# -*- coding: utf-8 -*-
TITLE = "What is an IPL Trade actually worth?"
BY    = "Omkar Walunj"

B = [
('t', "An IPL trade can change the trajectory of multiple teams with a single decision. Yet we still don’t have a proper way to price the trade itself."),
('h', 'How IPL Trade Values Works?'),
('t', "Example, If Mumbai Indians send a player to Chennai Super Kings, what has Chennai really received? To value a trade, we need to answer four questions: **What is the player worth? What is he worth to this particular team? What can the team realistically recover if he leaves? And is making the trade better than keeping him?**"),
('t', "IPL Trade Values answers these questions through five connected components: **Player Valuation → Team Fit → Replacement & Auction → Trade Economics → Counterfactual Simulation**. The framework starts by putting every player on a common scale using **Projected WAR (pWAR)**, then asks how that value changes when the player is placed inside a specific squad. It then models the auction pool and competition for replacements, thus calculates the possible recoverability from the auction, prices the financial side of the transaction, and finally compares the team in two worlds: **one where the trade happens and one where it doesn't.**"),
('h', 'What the model has to solve?'),
('t', "There are four problems to solve before a trade can be priced."), 
('t',"**Valuation:** What’s a player’s intrinsic worth, isolated from the team context."),
('t',"**Projection:** What is he likely to be worth next season and the one after that. This is much harder in a league as short and volatile as the IPL."), 
('t',"**Team Fit:** A player is never worth the same to every side. A team is basically twelve slots (once you factor in the impact player) and a set of constraints."),
('t',"**Replacement:** When you trade a player away you go into an auction with a limited purse, competing against nine other teams for a pool of players that nobody knows during the time of trades."),
('H', '(I) What is a player worth?'),
('h', 'Run Expectancy'),
('t', "For every ball, the model estimates the runs a team would be expected to score from the current over-and-wickets state. A player's **Runs Created** is then based on the difference between the actual outcome and that expected outcome, with wickets valued through the change in run expectancy between the state before and after the wicket."),
('i', 'wicket_value.png', 'Wicket value changes with the match state and remaining run expectancy.'),
('h', 'Context'),
('t', "The contribution is then adjusted for the context in which it occurred. The model accounts for **venue, leverage, innings, pace vs spin, and batter handedness**. Batting and bowling contributions are also linked through the same run-based framework, so the value created by one side is the value conceded by the other."),
('h', 'Replacement Level'),
('t', "The next question is: *better than whom?* I define replacement level as the contribution expected from a player who is realistically available to a franchise rather than an average IPL player. The model establishes a league-level replacement pool using playing-time-weighted player participation, with the top eight batters and six bowlers from each team forming the regular-player pool. The players below that level establish the replacement benchmark."),
('h', 'From Runs to WAR'),
('t', "The resulting contribution is converted from runs into wins. In the 2023–2026 data, approximately **5.9 runs correspond to one additional win per match**, or around **82.5 runs over a 14-match season**. WAR is then expressed relative to replacement: **Replacement = 0 WAR**. A regular player is around **1.5-2 WAR**, while the strongest players reach substantially higher values."),
('t', "For players with limited IPL records, the same framework is also applied to T20I data and blended according to the precision of the available information. The resulting measure is **Projected WAR (pWAR)**: the model's estimate of what the player is expected to contribute in the upcoming season."),
('H', '(II) What is he worth to this team?'),
('t', "A player's WAR tells us what he is worth in isolation. It does **not** tell us what he is worth to a particular team. Let's take Dewald Brevis' case. His WAR comes out at 1.12, so now, if we ask what he'd be worth to Mumbai Indians? Answer is almost nothing, as MI already have Rickelton and Will Jacks, both of whom are ahead of him. Bringing Brevis in results in an option for a position that's already covered."),
('i', 'brevis_four_teams.png', "Dewald Brevis's team-specific value across possible team contexts."),
('h', 'Slots are not equal'),
('t', "I treat a squad as a set of roles and slots rather than simply a collection of players. Different positions receive different amounts of exposure. An opener faces far more balls than a number eight, while a primary bowler contributes far more deliveries than a seventh bowling option. Therefore, the same improvement in pWAR can have very different value depending on **where the improvement occurs**. This exposure is combined with the estimated importance of each batting position and bowling phase when evaluating the team's needs."),
('i', 'slot_exposure.png', 'Slot exposure and role importance across the XI.'),
('t', "Thus, I built a **team-selection optimizer**. For every player, I mapped the role he can realistically perform. It respects the overseas limit, batting positions and bowling-phase coverage, and finds the best legal XII for each squad. So, a hole is not only just a player leaving, but also a slot where the best replacement player you have left is below what that position should deliver (calculated from the league average requirement for each role)."),
('t', "After we know this, the intuitive next step was to find: **What the team actually loses when a player leaves and how likely will the team recover that loss in the mini auction.**"),
('H', '(III) Can you just buy a replacement?'),
('t', "The trade window shuts before the release deadline, which shuts before the auction, so at the moment you're deciding, you don't know which players will even be available. I had to predict that pool in order to solve this problem. I trained a model on the 2023 to 2026 transitions using salary, share of matches played, performance against the average for that specific role, and squad depth in front of the player. The model outputs a probability for every contracted player. I set the cutoff separately for each role and nationality, choosing the probability that reproduces that group's own historical release rate. That produces the release list."),
('t', "Hardik Pandya's release probability lands at 0.78, which is worth noting given the trade talk, because it says Mumbai were probably moving on either way. At the other end, Sooryavanshi sits at 0.004 and Sai Sudharsan at 0.006 meaning nobody is releasing those two."),
('t', "For the auction itself I ran it as a sequential thing. First, I asked what kind of player the vacancy in that team actually needs. Each team bids what the player is worth to its remaining holes, and walks away when the price goes past that."),
('h', "Willingness to pay:"),
('t',"For any player, a team's ceiling is the improvement he makes to their best legal XII, converted into money. Take KKR's opening slot. If the man currently filling it projects at 1.85 pWAR and a 2.60 pWAR opener replaces him, the gain is **0.75 pWAR** and because an opener slot carries more of a season's exposure than most, that gain is worth roughly one and a half times what the same upgrade would be at number six."),
('t', "For converting this calculation in terms of money, I regressed what teams actually paid at the 2023, 2024 and 2026 mini-auctions against what each player was worth going in:"),
('t', 'price = **−₹1.24cr + ₹1.20cr × pWAR + ₹2.21cr × scarcity + ₹0.27cr × flexibility + ₹4.42cr × capped − ₹1.37cr × overseas**'),
('t', "So Kolkata's ceiling for that opener works out near **₹7 crore**, and above that they're overpaying, for that **0.75 pWAR** gain. Most of what a player costs in this market has very little to do with how many wins he is likely to produce."),
('h', "Which gives you a demand curve:"),
('t', "Sweep the quality of the player from bad to excellent and record what each team would pay at each level. Punjab won't pay a rupee for an opener until quality passes pWAR of the current openers, because their incumbent is already better than that. Kolkata start bidding at 0.18 pWAR because they have a genuine hole."),
('i', 'demand_curve.png', 'Team-specific auction demand curves for a role.'),
('h', 'Recovery Probability'),
('t', "This gives us the quantity I actually need for trade evaluation: **If this player leaves, what is the probability that the team can recover his value through the auction?** I separate this into the **Probability of filling the vacancy** and the **Probability of acquiring someone at least as good as the player lost.** A team can have a high probability of filling a role while having a much lower probability of replacing the actual quality it lost. That distinction is what produces the **recovery-value distribution** used in the trade evaluation."),
('H', '(IV) Putting a price on Trades'),
('t', "In Football or Baseball you buy a player and you can keep him for years. In IPL, due to a 3-year cycle the upcoming 2027 is the last season of the current cycle."),
('t', "**Surplus value:** (What he's worth - what he costs) summed over every year you hold him."),
('t', '**Surplus = (market-fair price − salary) + retention option value**'),
('t', "The first bracket is the guaranteed 2027 season. Market-fair price is:"),
('t', 'price = **−₹1.24cr + ₹1.20cr × pWAR + ₹2.21cr × scarcity + ₹0.27cr × flexibility + ₹4.42cr × capped − ₹1.37cr × overseas**'),
('t', "The second term is 2028 onward, and obviously it only exists if you retain him. So, it's only worth something when his projected value clears the slab price:"),
('f', r'\text{Option Value} = \sum_t \max\left(0,\text{Value}_t-\text{Slab Price}\right)\times \text{Discount}^{\,t}'),
('t', "where value\\_t is his value in the year 't' and slab price is at least ₹11 crore for a capped player and ₹4 crore for an uncapped one."),
('h', 'Opportunity Cost'),
('t', "If I spend ₹10 crore acquiring one player, that ₹10 crore isn't available for the other vacancies in my squad. So the financial calculation feeds back into the auction model through **opportunity cost**. So the trade is evaluated using **Player value + team fit + replacement value + financial surplus − opportunity cost**, rather than simply comparing the two players involved."),
('H', '(V) Does the team actually end up better off?'),
('t', "So now we've got something substantial- there's a value, a price, and a probability of recovery. The last thing left is to actually run the season and see what changes wrt States S1 and S2 as they're 2 different states of the same team based on the decision they took in the trade."),
('t',"S1: No trade so the player(s) stays. The team goes into the release process with its original squad, builds its purse, enters the auction and fills whatever vacancies it has."),
('t',"S2: Trade. The trade happens first which in turn changes the squad, the salaries and the vacancies. The release decisions are then applied to that new state, the purse changes accordingly, and the team enters the auction with a different set of needs."),
('h', 'Season Simulation'),
('t', "Then I simulated the season 2000 times for both states, and predicted the Win%, Playoff probability, Title Probability. The simulation produces distributions for **Regular-season win percentage, Playoff probability, Title probability, Final squad/XII value, and Asset value**."),
('t', "The trade's effect is then measured as the difference between the two states: **Δ=S2−S1**. So, for example: **Δ Playoff Probability=P(Playoffs∣S2)−P(Playoffs∣S1)** and similarly for the other outcomes."),
('h', 'Trade Utility'),
('t', "The final trade utility therefore asks a counterfactual question: **Is the team better off after making the trade than it would have been if the trade had never happened?** That is the final output of the framework."),
('h', 'The trade that already happened'),
('t', 'Pant to Delhi, Kuldeep to Lucknow.'),
('i', 'pant_kuldeep.png', 'The Rishabh Pant–Kuldeep Yadav trade evaluated through the framework.'),
('t', "Lucknow gained nine points of playoff probability by giving up their captain. Pant on ₹27 crore was costing them more than he was returning, and shedding that contract freed up a squad they could actually build in the auction. Delhi barely moved either way meaning their playoff probability won't change much by this trade."),
('t', """All I care is that if I can quantify what is being given up and show what has to be true for a trade to work, then I think I have got closer to answering the question I started with:"""),
('H', 'What is an IPL trade actually worth?'),
]
